# Generated by Django 4.1.6 on 2023-10-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_accesslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accessLevel',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
