# Generated by Django 4.1.6 on 2023-10-30 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0007_alter_user_accesslevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='To be confirmed', max_length=255)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicelocation')),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicesoffered')),
                ('userId', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
