# Generated by Django 4.1.6 on 2023-11-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userbookings_date_userbookings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accessLevel',
            field=models.CharField(default='user', max_length=255),
        ),
        migrations.AlterField(
            model_name='userbookings',
            name='status',
            field=models.CharField(default='Pending confirmation', max_length=255),
        ),
    ]
