# Generated by Django 4.1.6 on 2023-11-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileType',
            field=models.CharField(blank=True, choices=[('EMP', 'employee'), ('USER', 'user')], max_length=100, null=True),
        ),
    ]
