# Generated by Django 4.1.6 on 2023-11-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_profiletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileType',
        ),
        migrations.AddField(
            model_name='profile',
            name='emailAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
