# Generated by Django 4.1.6 on 2023-11-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_profiletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employmentStatus',
            field=models.BooleanField(default=True),
        ),
    ]
