# Generated by Django 4.1.6 on 2023-11-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_employmentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('TECH', 'Technician'), ('JRTECH', 'Jr. Technician'), ('SMM', 'Social Media Manager'), ('MM', 'Marketing Manager')], max_length=255, null=True),
        ),
    ]
