# Generated by Django 4.2.7 on 2023-11-13 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookings',
            name='assignedEmployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
