# Generated by Django 4.1.6 on 2023-11-03 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_alter_user_accesslevel_alter_userbookings_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('signInType', models.CharField(max_length=255)),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(max_length=255)),
                ('dateFrom', models.CharField(max_length=255)),
                ('dateTo', models.CharField(max_length=255)),
                ('note', models.CharField(default='', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
