# Generated by Django 4.1.6 on 2023-11-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesignin',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
