# Generated by Django 4.1.6 on 2023-11-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeesignin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
