# Generated by Django 4.2.7 on 2023-11-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_position'),
        ('employee', '0004_employeeleave_adminnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratePerHour', models.CharField(max_length=255)),
                ('hoursWorked', models.CharField(max_length=255)),
                ('bonus', models.CharField(max_length=255)),
                ('adjustments', models.CharField(max_length=255)),
                ('totalSalary', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
