# Generated by Django 4.2.7 on 2023-11-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeesalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
