# Generated by Django 4.2.7 on 2023-11-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employeesalary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='date',
            field=models.DateField(),
        ),
    ]
